image_dir: sample_dataset/
job_dir: sample_jobdir/

dataprep:
  run: True
  samples_file: sample_configfile.json
  resize: True

train:
  run: True
  cloud: False

evaluate:
  run: True
  report_html: True
  repor_pdf: False

cloud:
  cloud_tag: image_atm_example_tag
  provider: aws
  tf_dir: cloud/aws
  region: eu-west-1
  vpc_id: vpc-example
  instance_type: p2.xlarge
  bucket: s3://example-bucket
  destroy: True
