site_name: Image-ATM
site_author: idealo Data Science Team

nav:
    - Home: index.md
    - Getting Started: start.md
    - Examples:
      - Cats and Dogs: examples/cats_and_dogs.md
      - Imagenette: examples/imagenette.md
    - Documentation:
        - Client:
            - Client: client/client.md
            - Commands: client/commands.md
            - Config: client/config.md
        - Components:
            - Cloud: components/cloud.md
            - Data Preparation: components/data_prep.md
            - Training: components/training.md
            - Evaluation: components/evaluation.md
        - Handlers:
            - Data Generator: handlers/data_generator.md
            - Image Classifer: handlers/image_classifier.md
        - Scripts:
            - Run Cloud: scripts/run_cloud.md
            - Run Data Prep: scripts/run_data_prep.md
            - Run Training: scripts/run_training.md
            - Run Training Cloud: scripts/run_training_cloud.md
            - Run Evaluation: scripts/run_evaluation.md
    - Contribution: CONTRIBUTING.md
    - License: LICENSE.md
theme:
  name: 'material'
  palette:
    primary: 'red'
    accent: 'red'
  logo: 'img/logo.svg'
  favicon: 'img/favicon.ico'

repo_name: 'idealo/imageatm'
repo_url: 'https://github.com/idealo/imageatm'

markdown_extensions:
  - codehilite
